### PR TITLE
[jrubyscripting] Add ConfigurableService

### PR DESCRIPTION
**Pull request by jimtng**
I added ConfigurableService as suggested by wborn. I've also set the default to singlethread since that's the config that works for `scriptUnloaded` see https://github.com/boc-tothefuture/openhab-jruby/pull/397

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Ok.  I added the configurable service as well but haven't pushed it yet.  I will merge our two changes together where it makes sense.  

Have you tried single threaded?  I think it will cause a lot of issues:. https://github.com/boc-tothefuture/openhab-jruby/issues/46 has the discussion of the impact of each of these.

**Comment by jimtng** [comment]
I am running singlethread on my production environment as of today. So far everything seems to be running as normal.

**Comment by jimtng** [comment]
I don't fully understand the issue surrounding multi-threads with the jruby. Could you give an example scenario where singlethread would cause a problem?

If I understand it correctly:
- Each rule file gets its own scriptengine instance
- rules in different files should have no problems because they are running in a completely different script engine, like a separate 'virtual machine'
- multiple rules in the same file will share the same scriptengine, and can access the same instance variables and top-level variables. However they could be running concurrently through different threads, so modifications to variables that are visible to multiple rules (within the same file) are subject to multi-threading issues and therefore may need to be synchronised
- `threadsafe` option automatically manage the access to such variables, therefore no explicit synchronisations are required
- `singlethread` doesn't have such management

I could probably gain a better understanding if I spent some time digging into jruby's code but that would take time and some serious brain exercise.

**Comment by boc-tothefuture** [comment]
Merging this, moving discussion to thread context over to:
https://github.com/boc-tothefuture/openhab-jruby/issues/46

**Pull request merged**
