### PR TITLE
[jruby] fix script not reloading issue

### PR DESCRIPTION
**Pull request by jimtng**
This makes the binding to work on 3.2M2+ however as it is, it's broken because it doesn't actually perform the gem install. When the gem install is enabled, then we'll have the issue as described in https://github.com/boc-tothefuture/openhab-jruby/issues/334

I did some minor clean ups:
- Use the inherited logger from AbstractScriptEngineFactory https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/AbstractScriptEngineFactory.java#L36
- Provide a default value for the configurations. Although it's debatable whether we want to include the openhab-jruby gem by default?
- removed references to groovy in pom.xml

### CODE REVIEW

**Comment by jimtng** [comment]
@boc-tothefuture please take a look. Do you have an idea as to why the gem installer could cause problems?

**Comment by boc-tothefuture** [comment]
Good work in tracking down the issue and on general cleanup.

Seems bizarre that gem installer is a problem on script reloads.  Did you ever get a full stack trace?

**Comment by boc-tothefuture** [comment]
Let me look at this - will do my best to try and figure it out today.  In the meantime can you rebase against the branch I pushed up yesterday? It is the JRuby branch, there were some minor changes but more importantly it rebased against the latest openhab addons and squashed all the commits to a single one.  Git commit ID to rebase against is:  bcb8e89e2486d0acc4c2b34c17ed2427e4da625a

**Comment by boc-tothefuture** [comment]
I don't think we want to install our GEM by default - would probably be considered a conflict.
For the default paths you put in.  What happens if they don't exist?  Do we need to make them if they don't?
The Python binding seems to just place things next to the bindings - which I guess would always exist?

Lastly, on the GEM install, did you try and see what happens if you catch just the base Exception class?  I wonder if something is leaking.

**Comment by jimtng** [comment]
I've rebased and also removed the default value for the gem to install

**Comment by boc-tothefuture** [comment]
Ok.. I am going to merge it so we can be working off the same base. I will also probably push it back up with a rebase on main so this is squashed too..

**Comment by jimtng** [comment]
> For the default paths you put in.  What happens if they don't exist?  Do we need to make them if they don't?

I would imagine that nothing happens. They are merely used to set the GEM_HOME and RUBYLIB env vars.

I don't think we should make the directories if they don't exist. Someone could be just playing around installing the addon and deleting it straight away and they'll have new directories that they aren't aware of.

**Pull request merged**
