### PR TITLE
update jruby to 9.3.1.0

### PR DESCRIPTION
**Pull request by ccutrer**
I'm currently running the full cucumber suite of openhab-scripting against this PR with OpenHAB 3.2.0.M3. So far no failures...

### CODE REVIEW

**Comment by ccutrer** [comment]
* cucumber features/changed_duration.feature:182 is failing. log:
```
2021-10-24 22:14:17.741 [TRACE] [23.jruby.OpenHAB::Core::EntityLookup] - Looking up item(String_One)
2021-10-24 22:14:17.741 [TRACE] [23.jruby.OpenHAB::Core::EntityLookup] - Looking up item(String_One)
2021-10-24 22:14:17.741 [TRACE] [obj.OpenHAB.DSL.Rules.AutomationRule] - Executing rule 'Changed String' trigger block with item (TWO)
2021-10-24 22:14:17.741 [TRACE] [23.jruby.OpenHAB::Core::EntityLookup] - Looking up item(String_One)
2021-10-24 22:14:17.741 [INFO ] [jsr223.jruby.Object                 ] - Trigger Delay Fired
2021-10-24 22:14:21.831 [DEBUG] [rt.internal.loader.ScriptFileWatcher] - Dequeued file:/Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211024-91237-e7afmn.rb
2021-10-24 22:14:21.833 [TRACE] [jsr223.jruby.Object                 ] - Script unloaded
2021-10-24 22:14:21.833 [TRACE] [obj.OpenHAB.DSL.Rules.AutomationRule] - Cancelling 1 Trigger Delays(s) for rule 'Changed String'
2021-10-24 22:14:21.834 [TRACE] [jsr223.jruby.OpenHAB::DSL::Timers   ] - Cancelling 0 timers
```
 * cucumber features/metadata.feature:188 is failing, cause actual output is `TestSwitch namespace test is: value="foo" config={bar=baz}` (looks like the type is slightly different?)

more tests are still running...

**Comment by boc-tothefuture** [comment]
@ccutrer for some reason I got NO notification that you create this PR.. and I created my own.  with other changes in it..  ughh

**Comment by boc-tothefuture** [comment]
@ccutrer can you rebase and see if any of these changes are still needed?

**Comment by ccutrer** [comment]
The metadata tests are passing now (with my build from this morning that's also in my production instance). And the timer cancelation tests are now known bad in my dev environment. Since you already did it in another commit, I'm just going to close this PR and call it good.

**Pull request closed without merging**
